name: CI
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
jobs:
  run-test:
    name: Try build and run unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Npm install
        uses: ./.github/actions
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8
      - name: Restore cached .nx
        id: cache-nx-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .nx
          key: ${{ runner.os }}-nx-${{ steps.branch-names.outputs.current_branch }}
      - run: git branch --track main origin/master
      - name: Test
        env:
          NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
        run: npx nx affected -t test --parallel=3 --exclude='json-api-front,json-api-server,json-api-server-e2e,json-shared-type,database,@nestjs-json-api/source,type-for-rpc'
      - name: Build
        env:
          NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
        run: npx nx affected -t build --exclude='json-api-front,json-api-server,json-api-server-e2e,json-shared-type,database,@nestjs-json-api/source,type-for-rpc'
      - name: Save cached .nx
        id: cache-dependencies-save
        uses: actions/cache/save@v4
        with:
          path: |
            .nx
          key: ${{ steps.cache-nx-restore.outputs.cache-primary-key }}
  run-e2e-test:
    runs-on: ubuntu-latest
    name: Try run e2e test
    needs:
      - run-test
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: json-api-db
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Npm install
        uses: ./.github/actions
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8
      - name: Restore cached .nx
        id: cache-nx-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .nx
          key: ${{ runner.os }}-nx-${{ steps.branch-names.outputs.current_branch }}
      - run: git branch --track main origin/master
      - run: npm run typeorm migration:run
      - run: npm run seed:run
      - run: npx nx affected -t e2e --parallel=1
      - run: npx nx affected -t e2e-micro --parallel=1
      - name: Save cached .nx
        id: cache-dependencies-save
        uses: actions/cache/save@v4
        with:
          path: |
            .nx
          key: ${{ steps.cache-nx-restore.outputs.cache-primary-key }}
